name = "developer-portfolio"
compatibility_date = "2024-09-16"
pages_build_output_dir = "./dist"

[[kv_namespaces]]
binding = "PORTFOLIO_DATA"
id = "<YOUR_KV_NAMESPACE_ID>"
preview_id = "<YOUR_KV_PREVIEW_NAMESPACE_ID>"
